# Generated by Django 3.2.4 on 2023-12-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp89', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Doc/', verbose_name='壁纸图片')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docImgs', to='serviceApp89.doc', verbose_name='资料')),
            ],
            options={
                'verbose_name': '壁纸',
                'verbose_name_plural': '壁纸',
            },
        ),
    ]
