# Generated by Django 3.2.7 on 2023-11-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp89', '0003_auto_20231017_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2023-11-13', max_length=20, verbose_name='出生日期'),
        ),
    ]
