# Generated by Django 3.2.4 on 2023-12-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp89', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-publishDate',), 'verbose_name': '道具', 'verbose_name_plural': '道具'},
        ),
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': '道具图片', 'verbose_name_plural': '道具图片'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='道具价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('哆啦道具', '哆啦道具')], max_length=50, verbose_name='道具类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='道具名称'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Product/', verbose_name='道具图片'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productApp89.product', verbose_name='道具'),
        ),
    ]
